// ── FALLBACK DATA ─────────────────────────────────────────────────────────────
export const FB = {
  english: {
    words: [
      "the",
      "be",
      "to",
      "of",
      "and",
      "a",
      "in",
      "that",
      "have",
      "it",
      "for",
      "not",
      "on",
      "with",
      "he",
      "as",
      "you",
      "do",
      "at",
      "this",
      "but",
      "his",
      "by",
      "from",
      "they",
      "we",
      "say",
      "her",
      "she",
      "or",
      "an",
      "will",
      "my",
      "one",
      "all",
      "would",
      "there",
      "what",
      "so",
      "up",
      "out",
      "if",
      "about",
      "who",
      "get",
      "which",
      "go",
      "me",
      "when",
      "make",
      "can",
      "like",
      "time",
      "no",
      "just",
      "him",
      "know",
      "take",
      "people",
      "into",
      "year",
      "your",
      "good",
      "some",
      "could",
      "them",
      "see",
      "other",
      "than",
      "then",
      "now",
      "look",
      "only",
      "come",
      "its",
      "over",
      "think",
      "also",
      "back",
      "after",
      "use",
      "two",
      "how",
      "our",
      "work",
      "first",
      "well",
      "way",
      "even",
      "new",
      "want",
      "any",
      "these",
      "give",
      "day",
      "most",
      "us",
      "great",
      "world",
      "still",
      "long",
      "down",
      "move",
      "keep",
      "put",
      "change",
      "point",
      "play",
      "small",
      "number",
      "off",
      "always",
      "turn",
      "show",
      "large",
      "often",
      "hand",
      "high",
      "place",
      "hold",
      "real",
      "life",
      "few",
      "north",
      "open",
      "seem",
      "together",
      "next",
      "white",
      "children",
      "begin",
      "got",
      "walk",
      "example",
      "ease",
      "paper",
      "group",
      "music",
      "those",
      "both",
      "mark",
      "book",
      "letter",
      "until",
      "mile",
      "river",
      "car",
      "feet",
      "care",
      "second",
      "enough",
      "plain",
      "girl",
      "usual",
      "young",
      "ready",
      "above",
      "ever",
      "red",
      "list",
      "though",
      "feel",
      "talk",
      "bird",
      "soon",
      "body",
      "dog",
      "family",
      "direct",
      "pose",
      "leave",
    ],
    sentences: [
      "The quick brown fox jumps over the lazy dog.",
      "Pack my box with five dozen liquor jugs.",
      "How vexingly quick daft zebras jump.",
      "The five boxing wizards jump quickly.",
      "Sphinx of black quartz, judge my vow.",
      "Two driven jocks help fax my big quiz.",
      "The job requires extra pluck and zeal from every young wage earner.",
      "A mad boxer shot a quick gloved jab to the jaw of his dizzy opponent.",
      "Sixty zippers were quickly picked from the woven jute bag.",
      "We promptly judged antique ivory buckles for the next prize.",
    ],
    software: [
      "function",
      "variable",
      "const",
      "let",
      "return",
      "export",
      "import",
      "class",
      "interface",
      "async",
      "await",
      "promise",
      "callback",
      "array",
      "object",
      "string",
      "boolean",
      "number",
      "null",
      "undefined",
      "typeof",
      "instanceof",
      "prototype",
      "constructor",
      "extends",
      "implements",
      "override",
      "readonly",
      "private",
      "public",
      "namespace",
      "module",
      "require",
      "package",
      "deploy",
      "repository",
      "commit",
      "branch",
      "merge",
      "request",
      "review",
      "refactor",
      "debug",
      "compile",
      "runtime",
      "framework",
      "library",
      "dependency",
      "version",
      "release",
      "sprint",
      "agile",
      "backend",
      "frontend",
      "database",
      "schema",
      "endpoint",
      "middleware",
      "authentication",
      "authorization",
      "token",
      "cookie",
      "session",
      "cache",
      "queue",
      "thread",
      "process",
      "memory",
    ],
    customer: [
      "account",
      "service",
      "support",
      "issue",
      "resolve",
      "ticket",
      "escalate",
      "refund",
      "billing",
      "subscription",
      "password",
      "reset",
      "verify",
      "confirm",
      "update",
      "cancel",
      "renewal",
      "invoice",
      "payment",
      "charge",
      "transaction",
      "order",
      "shipping",
      "delivery",
      "tracking",
      "return",
      "exchange",
      "warranty",
      "policy",
      "terms",
      "agreement",
      "feedback",
      "satisfaction",
      "experience",
      "complaint",
      "apology",
      "supervisor",
      "manager",
      "department",
      "priority",
      "urgent",
      "escalation",
      "resolution",
      "follow-up",
      "response",
      "inquiry",
      "request",
      "assistance",
      "availability",
      "status",
    ],
    medical: [
      "patient",
      "diagnosis",
      "treatment",
      "prescription",
      "medication",
      "dosage",
      "symptoms",
      "examination",
      "laboratory",
      "pathology",
      "radiology",
      "surgical",
      "procedure",
      "anesthesia",
      "cardiovascular",
      "respiratory",
      "neurological",
      "orthopedic",
      "pediatric",
      "oncology",
      "immunology",
      "pharmacology",
      "epidemiology",
      "prognosis",
      "therapy",
      "rehabilitation",
      "consultation",
      "referral",
      "discharge",
      "admission",
      "chronic",
      "acute",
      "benign",
      "malignant",
      "hypertension",
      "diabetes",
      "infection",
      "inflammation",
      "fracture",
      "laceration",
      "suture",
      "biopsy",
      "ultrasound",
      "electrocardiogram",
    ],
    legal: [
      "agreement",
      "contract",
      "litigation",
      "plaintiff",
      "defendant",
      "jurisdiction",
      "testimony",
      "evidence",
      "counsel",
      "statute",
      "regulation",
      "compliance",
      "liability",
      "indemnity",
      "arbitration",
      "settlement",
      "discovery",
      "deposition",
      "affidavit",
      "amendment",
      "clause",
      "provision",
      "warranty",
      "obligation",
      "consideration",
      "breach",
      "damages",
      "injunction",
      "remedy",
      "appeal",
      "constitution",
      "legislation",
      "ordinance",
      "subpoena",
      "verdict",
      "judgment",
      "prosecution",
      "defense",
      "attorney",
      "paralegal",
    ],
    student: [
      "thesis",
      "hypothesis",
      "analysis",
      "synthesis",
      "argument",
      "evidence",
      "conclusion",
      "introduction",
      "methodology",
      "bibliography",
      "citation",
      "reference",
      "abstract",
      "paragraph",
      "research",
      "experiment",
      "observation",
      "theory",
      "principle",
      "concept",
      "definition",
      "example",
      "discussion",
      "evaluation",
      "reflection",
      "comparison",
      "contrast",
      "perspective",
      "interpretation",
      "critique",
      "assignment",
      "deadline",
      "professor",
      "lecture",
      "seminar",
      "examination",
      "dissertation",
      "curriculum",
      "syllabus",
      "academic",
    ],
    numbers: [
      "1234567890",
      "98765 43210",
      "12 34 56 78",
      "100 200 300",
      "1000 2000",
      "3.14159",
      "2.71828",
      "1.61803",
      "42 56 78 90",
      "11 22 33 44",
      "555 666 777",
      "123 456 789",
      "0.001 0.01 0.1",
      "1024 2048 4096",
      "360 180 90 45",
    ],
    symbols: [
      "!@#$%^&*()",
      "+-*/=<>?",
      "{[()]}",
      "\"'`~\\|",
      "!!! ??? ...",
      "@email.com",
      "#hashtag",
      "$price %off",
      "^power &and",
      "*star (open)",
      "---===+++",
      "<html></html>",
      "/* comment */",
      "// inline",
      "::selector",
      "->arrow =>",
    ],
    numbersSymbols: [
      "1+1=2",
      "100% done",
      "$49.99",
      "2^10=1024",
      "a@b.com",
      "#1 best!",
      "3*4=12",
      "pi=3.14",
      "50% off $20",
      "2024-01-15",
      "v2.0.1",
      "100/5=20",
      "x^2+y^2=r^2",
      "!important",
      "@media(max)",
    ],
    alphabetsNumbers: [
      "abc123",
      "xyz789",
      "cat5 dog7",
      "mix1ed2",
      "type3fast",
      "code4fun",
      "speed5test",
      "key6board",
      "fast7type",
      "learn8now",
      "skill9up",
      "zero0hero",
      "react18",
      "node20",
      "python3",
    ],
    alphabetsNumbersSymbols: [
      "hello@world.com",
      "v2.0!",
      "$100+tax",
      "user#1234",
      "pass@word1!",
      "2+2=4!",
      "type&write",
      "fast*speed",
      "100% correct!",
      "open(source)",
      "key=value;",
      "git@github.com",
      "price=$9.99",
      "top#1!",
      "done=>true",
    ],
    code: {
      javascript: [
        `const fibonacci = (n) => {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n};`,
        `async function fetchData(url) {\n  try {\n    const res = await fetch(url);\n    return await res.json();\n  } catch (err) {\n    console.error(err);\n  }\n}`,
        `const debounce = (fn, delay) => {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay);\n  };\n};`,
      ],
      python: [
        `def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + [pivot] + quicksort(right)`,
        `class Stack:\n    def __init__(self):\n        self.items = []\n    def push(self, item):\n        self.items.append(item)\n    def pop(self):\n        return self.items.pop() if self.items else None`,
      ],
      java: [
        `public class BinarySearch {\n  public static int search(int[] arr, int target) {\n    int left = 0, right = arr.length - 1;\n    while (left <= right) {\n      int mid = left + (right - left) / 2;\n      if (arr[mid] == target) return mid;\n      else if (arr[mid] < target) left = mid + 1;\n      else right = mid - 1;\n    }\n    return -1;\n  }\n}`,
      ],
      cpp: [
        `#include <iostream>\nusing namespace std;\nint factorial(int n) {\n    if (n == 0 || n == 1) return 1;\n    return n * factorial(n - 1);\n}\nint main() {\n    cout << factorial(10) << endl;\n    return 0;\n}`,
      ],
      rust: [
        `fn is_prime(n: u64) -> bool {\n    if n < 2 { return false; }\n    for i in 2..=(n as f64).sqrt() as u64 {\n        if n % i == 0 { return false; }\n    }\n    true\n}`,
      ],
    },
  },
  hindi: {
    words: [
      "और",
      "है",
      "में",
      "की",
      "को",
      "का",
      "से",
      "हम",
      "वे",
      "यह",
      "पर",
      "एक",
      "तो",
      "जो",
      "भी",
      "के",
      "लिए",
      "था",
      "हो",
      "कि",
      "आप",
      "यहाँ",
      "वहाँ",
      "साथ",
      "बात",
      "करना",
      "समय",
      "दिन",
      "लोग",
      "काम",
      "घर",
      "देश",
      "नाम",
      "आना",
      "जाना",
      "देखना",
      "कहना",
      "बड़ा",
      "छोटा",
      "अच्छा",
      "नया",
      "पुराना",
      "सही",
      "गलत",
      "कभी",
      "सब",
      "खुद",
      "बहुत",
      "कुछ",
      "जब",
      "तब",
      "कहाँ",
      "क्यों",
      "कैसे",
      "कितना",
      "इसलिए",
      "हाँ",
      "नहीं",
      "शायद",
      "अभी",
      "फिर",
      "बाद",
      "पहले",
      "ऊपर",
      "नीचे",
      "अंदर",
      "बाहर",
    ],
    sentences: [
      "आज का दिन बहुत अच्छा है।",
      "हम सब मिलकर काम करते हैं।",
      "ज्ञान ही शक्ति है।",
      "समय बहुत कीमती है।",
      "परिश्रम से सफलता मिलती है।",
      "जीवन में आगे बढ़ते रहो।",
      "हर दिन एक नया अवसर है।",
      "मेहनत का फल मीठा होता है।",
    ],
  },
  spanish: {
    words: [
      "el",
      "la",
      "de",
      "que",
      "y",
      "a",
      "en",
      "un",
      "ser",
      "se",
      "no",
      "haber",
      "por",
      "con",
      "su",
      "para",
      "como",
      "estar",
      "tener",
      "le",
      "lo",
      "todo",
      "pero",
      "más",
      "hacer",
      "o",
      "poder",
      "decir",
      "este",
      "ir",
      "otro",
      "ese",
      "si",
      "me",
      "ya",
      "ver",
      "porque",
      "dar",
      "cuando",
      "él",
      "muy",
      "sin",
      "vez",
      "mucho",
      "saber",
      "qué",
      "sobre",
      "mi",
      "algunos",
      "tiempo",
      "año",
      "bien",
      "país",
      "gran",
      "mismo",
      "donde",
      "número",
      "vida",
      "forma",
      "parte",
      "lugar",
      "mundo",
      "casa",
      "mano",
      "hombre",
      "mujer",
      "agua",
      "trabajo",
      "ciudad",
    ],
    sentences: [
      "El tiempo es oro.",
      "La práctica hace al maestro.",
      "El conocimiento es poder.",
      "Cada día es una nueva oportunidad.",
      "La perseverancia es la clave del éxito.",
      "Nunca es tarde para aprender.",
      "El trabajo duro siempre da frutos.",
      "La vida es bella y llena de sorpresas.",
    ],
  },
};

// ── DRILL FALLBACK DATA ──────────────────────────────────────────────────────
// For each letter/number/symbol, words/pairs containing them
export const DRILL_FB = {};

// Build single-char drills
const alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
const numbers = "0123456789".split("");
const symbols = [
  "!",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
  "(",
  ")",
  "_",
  "+",
  "-",
  "=",
  "[",
  "]",
  "{",
  "}",
  ";",
  "'",
  ":",
  '"',
  ",",
  ".",
  "<",
  ">",
  "/",
  "?",
  "\\",
  "|",
  "`",
  "~",
];

// Words containing each letter (from fallback pool)
const allEnglishWords = FB.english.words;

alphabet.forEach((letter) => {
  const containing = allEnglishWords.filter((w) => w.includes(letter));
  const words =
    containing.length > 0 ? containing : allEnglishWords.slice(0, 20);
  DRILL_FB[letter] = words.slice(0, 30);
});

numbers.forEach((num) => {
  // Generate sequences with that number
  const seqs = [];
  for (let i = 0; i < 20; i++) {
    const prefix = allEnglishWords[i % allEnglishWords.length];
    seqs.push(`${prefix}${num}`);
    seqs.push(`${num}${prefix.slice(0, 3)}`);
  }
  DRILL_FB[num] = seqs.slice(0, 30);
});

symbols.forEach((sym) => {
  const seqs = [];
  const safe = sym.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  for (let i = 0; i < 15; i++) {
    seqs.push(`test${sym}go`);
    seqs.push(`word${sym}end`);
    seqs.push(`${sym}type`);
  }
  DRILL_FB[sym] = seqs.slice(0, 20);
});

// Common bigram pairs drill data
const COMMON_PAIRS = [
  "th",
  "he",
  "in",
  "en",
  "nt",
  "re",
  "er",
  "an",
  "ti",
  "es",
  "on",
  "at",
  "se",
  "nd",
  "or",
  "ar",
  "al",
  "te",
  "co",
  "de",
  "to",
  "ra",
  "et",
  "ed",
  "it",
  "sa",
  "em",
  "ro",
  "in",
  "ne",
];
COMMON_PAIRS.forEach((pair) => {
  const containing = allEnglishWords.filter((w) => w.includes(pair));
  DRILL_FB[pair] = (
    containing.length > 8 ? containing : [...containing, ...allEnglishWords]
  ).slice(0, 30);
});

export { COMMON_PAIRS };

// ── FINGER MAP ───────────────────────────────────────────────────────────────
export const FINGER_KEY_MAP = {
  left_pinky: ["q", "a", "z", "1", "!", "`", "~", "tab", "caps"],
  left_ring: ["w", "s", "x", "2", "@"],
  left_middle: ["e", "d", "c", "3", "#"],
  left_index: ["r", "f", "v", "t", "g", "b", "4", "$", "5", "%"],
  right_index: ["y", "h", "n", "u", "j", "m", "6", "^", "7", "&"],
  right_middle: ["i", "k", ",", "8", "*"],
  right_ring: ["o", "l", ".", "9", "("],
  right_pinky: [
    "p",
    ";",
    "[",
    "]",
    "0",
    ")",
    "-",
    "_",
    "=",
    "+",
    "\\",
    "|",
    "'",
    '"',
    "/",
    "?",
  ],
  thumbs: [" "],
};

export function fingerForKey(key) {
  const k = (key || "").toLowerCase();
  for (const [finger, keys] of Object.entries(FINGER_KEY_MAP)) {
    if (keys.includes(k)) return finger;
  }
  return null;
}

// ── UTILS ────────────────────────────────────────────────────────────────────
export function lsGet(k) {
  try {
    return JSON.parse(localStorage.getItem(k));
  } catch {
    return null;
  }
}
export function lsSet(k, v) {
  try {
    localStorage.setItem(k, JSON.stringify(v));
  } catch {}
}
export function shuffle(a) {
  const b = [...a];
  for (let i = b.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [b[i], b[j]] = [b[j], b[i]];
  }
  return b;
}
export function calcWPM(correctChars, seconds) {
  if (!seconds || seconds < 1) return 0;
  return Math.round(correctChars / 5 / (seconds / 60));
}
export function calcAccuracy(correct, total) {
  if (!total) return 100;
  return Math.round((correct / total) * 100);
}
export function countCorrect(input, target) {
  let c = 0;
  for (let i = 0; i < input.length; i++) if (input[i] === target[i]) c++;
  return c;
}
export function uid() {
  return "guest_" + Math.random().toString(36).slice(2, 10);
}

export async function apiGet(endpoint, fallback) {
  const cached = lsGet("api_" + endpoint.replace(/\//g, "_"));
  try {
    const res = await fetch(`/api${endpoint}`, {
      signal: AbortSignal.timeout(4000),
    });
    if (!res.ok) throw new Error();
    const data = await res.json();
    lsSet("api_" + endpoint.replace(/\//g, "_"), data);
    return data;
  } catch {
    return cached ?? fallback;
  }
}
export async function apiPost(endpoint, body) {
  try {
    const res = await fetch(`/api${endpoint}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) throw new Error();
    return await res.json();
  } catch {
    return null;
  }
}

export function generateText(lang, mode, codeLang, count = 80, caps = false) {
  const fb = FB[lang] || FB.english;
  if (mode === "code") {
    const snips = fb.code?.[codeLang] || FB.english.code.javascript;
    return shuffle(snips).slice(0, 2).join("\n\n");
  }
  const pool = fb[mode] || fb.words || FB.english.words;
  let result;
  if (Array.isArray(pool)) {
    let r = [];
    while (r.length < count) r = r.concat(shuffle(pool));
    result = r.slice(0, count).join(" ");
  } else {
    result = String(pool);
  }
  if (caps) result = result.toUpperCase();
  return result;
}

export const ALPHABETIC_MODES = [
  "words",
  "sentences",
  "software",
  "customer",
  "medical",
  "legal",
  "student",
  "alphabetsNumbers",
  "alphabetsNumbersSymbols",
  "code",
];

export const DURATIONS = [
  { label: "30s", value: 30, type: "quick" },
  { label: "1m", value: 60, type: "consistency" },
  { label: "2m", value: 120, type: "consistency" },
  { label: "5m", value: 300, type: "endurance" },
  { label: "10m", value: 600, type: "endurance" },
  { label: "15m", value: 900, type: "endurance" },
  { label: "60m", value: 3600, type: "productivity" },
];

export const CONTENT_MODES = [
  { id: "words", label: "Words", group: "text" },
  { id: "sentences", label: "Sentences", group: "text" },
  { id: "software", label: "Software Dev", group: "professional" },
  { id: "customer", label: "Customer Support", group: "professional" },
  { id: "medical", label: "Medical", group: "professional" },
  { id: "legal", label: "Legal", group: "professional" },
  { id: "student", label: "Essay", group: "professional" },
  { id: "numbers", label: "Numbers", group: "special" },
  { id: "symbols", label: "Symbols", group: "special" },
  { id: "numbersSymbols", label: "Num + Sym", group: "special" },
  { id: "alphabetsNumbers", label: "Alpha + Num", group: "special" },
  { id: "alphabetsNumbersSymbols", label: "All Mix", group: "special" },
  { id: "code", label: "Code", group: "code" },
];

export const LANGS = [
  { id: "english", label: "English", flag: "🇬🇧" },
  { id: "hindi", label: "हिंदी", flag: "🇮🇳" },
  { id: "spanish", label: "Español", flag: "🇪🇸" },
];

export const CODE_LANGS = ["javascript", "python", "java", "cpp", "rust"];

export const ACHIEVEMENTS_DEF = [
  {
    id: "first_test",
    name: "First Keystroke",
    desc: "Complete first test",
    icon: "🎯",
    points: 10,
  },
  {
    id: "wpm_50",
    name: "Speed Demon",
    desc: "Reach 50 WPM",
    icon: "⚡",
    points: 50,
  },
  {
    id: "wpm_80",
    name: "Lightning Fingers",
    desc: "Reach 80 WPM",
    icon: "🌩️",
    points: 100,
  },
  {
    id: "wpm_100",
    name: "Centurion",
    desc: "Reach 100 WPM",
    icon: "🚀",
    points: 200,
  },
  {
    id: "accuracy_95",
    name: "Precision Master",
    desc: "95%+ accuracy",
    icon: "🎯",
    points: 75,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    desc: "7-day streak",
    icon: "🔥",
    points: 150,
  },
  {
    id: "tests_10",
    name: "Dedicated",
    desc: "10 tests done",
    icon: "📝",
    points: 30,
  },
];

export const SKILL_TREE = [
  { id: "basics", name: "Fundamentals", xpReq: 0 },
  { id: "speed", name: "Speed Burst", xpReq: 500 },
  { id: "accuracy", name: "Precision", xpReq: 1000 },
  { id: "endurance", name: "Endurance", xpReq: 2000 },
  { id: "code_typing", name: "Code Typing", xpReq: 3000 },
  { id: "master", name: "Master Typist", xpReq: 5000 },
];

export const LS_KEY = "tc_user_data";
